Removes tmp files
omniboard/firebase-backups pull request #6
Opened 2017-02-13 16:56 UTC by tbowler

When the backups are created the temp files are saved to the server or hosted location temp files are created. Eventually you will run out of space. 

After the backup is complete this will delete the compressed file.

2017-02-13 21:43 UTC, RobinDaugherty requested changes

2017-02-13 21:43 UTC, RobinDaugherty commented on firebaseBackup.js
>                }, function(){
We should not be treating a failure the same as success.

2017-02-14 14:47 UTC, tbowler commented on firebaseBackup.js
>                }, function(){
@RobinDaugherty I completely agree seen here: https://github.com/omniboard/firebase-backups/pull/6/commits/76738ade0585aaa7266dbb0a7e32a23369cbb9a2

2017-02-14 18:03 UTC, RobinDaugherty requested changes

2017-02-14 18:03 UTC, RobinDaugherty commented on firebaseBackup.js
>                }, function(){
I see that you're rejecting it, but you're still treating this as success. The command needs to fail if the S3 upload fails.

2017-02-15 17:41 UTC, RobinDaugherty approved these changes

2017-02-15 17:42 UTC, merged